-- Add migration script here

CREATE TABLE USER (
  ID INTEGER PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL UNIQUE,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  SALT VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
