-- SQLITE
PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE NOTE (
  ID INTEGER PRIMARY KEY,
  TITLE TEXT NOT NULL,
  CONTENT TEXT,
  CREATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  PARENT_TRIP INTEGER NOT NULL
);

CREATE INDEX NOTE_PARENT_TRIP ON NOTE(PARENT_TRIP);
CREATE INDEX NOTE_TITLE ON NOTE(TITLE);

CREATE TABLE PLACE (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT,
  CREATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  PARENT_TRIP INTEGER NOT NULL
  -- GOOGLE MAPS URL OR SOMETHING
);

CREATE INDEX PLACE_PARENT_TRIP ON PLACE(PARENT_TRIP);

CREATE TABLE IF NOT EXISTS LIST (
  ID INTEGER PRIMARY KEY,
  TITLE TEXT NOT NULL,
  PARENT_TRIP INTEGER NOT NULL,
  CHECKLIST BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX LIST_PARENT_TRIP ON LIST(PARENT_TRIP);

CREATE TABLE IF NOT EXISTS ITEM (
  ID INTEGER PRIMARY KEY,
  CONTENT TEXT,
  COMPLETE BOOLEAN NOT NULL DEFAULT FALSE,
  ORDINALITY INT NOT NULL, 
  PARENT_LIST INTEGER NOT NULL,

  FOREIGN KEY(PARENT_LIST) REFERENCES LIST(ID)
);

CREATE INDEX ITEM_PARENT_LIST ON ITEM(PARENT_LIST);

CREATE TABLE IF NOT EXISTS TRIP (
  ID INTEGER PRIMARY KEY,
  USER_ID INTEGER NOT NULL,
  TITLE TEXT NOT NULL,
  IMAGE TEXT, -- URL
  START_DATE INTEGER NOT NULL,
  END_DATE INTEGER NOT NULL,
  CREATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX USER_ID_TRIP ON TRIP(USER_ID);

-- Add a bunch of sample data to trips
insert into TRIP (USER_ID, TITLE, IMAGE, START_DATE, END_DATE) values (1, 'Japan', '/public/japan.avif', 1640995200, 1641081600);
insert into TRIP (USER_ID, TITLE, IMAGE, START_DATE, END_DATE) values (1, 'Europe', '/public/europe.avif', 1640995200, 1641081600);
insert into TRIP (USER_ID, TITLE, IMAGE, START_DATE, END_DATE) values (1, 'Monterrey', '/public/monterrey.avif', 1640995200, 1641081600);
insert into TRIP (USER_ID, TITLE, IMAGE, START_DATE, END_DATE) values (1, 'CDMX', '/public/cdmx.avif', 1640995200, 1641081900);


INSERT INTO LIST (TITLE, PARENT_TRIP) VALUES ('Checklisr', 1), ('Itinerary', 1), ('Split Costs', 1), ('Fly.io', 1);

INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('Add item to lists ',1,0,1);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('remove item from list',1,1,1);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('Create new list ',0,3,1);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('reorder items in list',1,2,1);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('CRDT',0,0,4);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('Websocket setup to comunicate changes',0,1,4);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('Move completed items to a gray section when complete',0,4,1);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('handle big texts',0,5,1);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('modificar titulo',1,7,1);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('1',0,3,2);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('2',0,0,2);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('3',0,1,2);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('4hola ',0,2,2);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('5',0,4,2);
INSERT INTO ITEM (CONTENT, COMPLETE, ORDINALITY, PARENT_LIST) VALUES('styles',0,6,1);
