-- SQLITE
PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE NOTE (
  ID INTEGER PRIMARY KEY,
  TITLE TEXT NOT NULL,
  CONTENT TEXT,
  CREATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  PARENT_TRIP INTEGER NOT NULL
);

CREATE INDEX NOTE_PARENT_TRIP ON NOTE(PARENT_TRIP);
CREATE INDEX NOTE_TITLE ON NOTE(TITLE);

CREATE TABLE PLACE (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT,
  CREATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  PARENT_TRIP INTEGER NOT NULL
  -- GOOGLE MAPS URL OR SOMETHING
);

CREATE INDEX PLACE_PARENT_TRIP ON PLACE(PARENT_TRIP);

CREATE TABLE IF NOT EXISTS LIST (
  ID INTEGER PRIMARY KEY,
  TITLE TEXT NOT NULL,
  PARENT_TRIP INTEGER NOT NULL,
  CREATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX LIST_PARENT_TRIP ON LIST(PARENT_TRIP);

CREATE TABLE IF NOT EXISTS ITEM (
  ID INTEGER PRIMARY KEY,
  CONTENT TEXT,
  COMPLETE BOOLEAN NOT NULL DEFAULT FALSE,

  ORDINALITY INT NOT NULL, 
  PARENT_LIST INTEGER NOT NULL,
  FOREIGN KEY(PARENT_LIST) REFERENCES LIST(ID)
);

CREATE INDEX ITEM_PARENT_LIST ON ITEM(PARENT_LIST);

CREATE TABLE IF NOT EXISTS TRIP (
  ID INTEGER PRIMARY KEY,
  USER_ID INTEGER NOT NULL,
  TITLE TEXT NOT NULL,
  IMAGE TEXT, -- URL
  START_DATE INTEGER NOT NULL,
  END_DATE INTEGER NOT NULL,
  CREATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT INTEGER DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX USER_ID_TRIP ON TRIP(USER_ID);

-- Add a bunch of sample data to trips
insert into TRIP (USER_ID, TITLE, IMAGE, START_DATE, END_DATE) values (1, 'Japan', '/public/japan.avif', 1640995200, 1641081600);
insert into TRIP (USER_ID, TITLE, IMAGE, START_DATE, END_DATE) values (1, 'Europe', '/public/europe.avif', 1640995200, 1641081600);
insert into TRIP (USER_ID, TITLE, IMAGE, START_DATE, END_DATE) values (1, 'Monterrey', '/public/monterrey.avif', 1640995200, 1641081600);
insert into TRIP (USER_ID, TITLE, IMAGE, START_DATE, END_DATE) values (1, 'CDMX', '/public/cdmx.avif', 1640995200, 1641081900);
