// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Item { id: bigint, content: string | null, complete: boolean, ordinality: bigint, parent_list: bigint, }
