// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";

export interface List { id: bigint, title: string, items: Array<Item>, }
