// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Note = { id: number, title: string, content: string | null, created_at: number, updated_at: number, parent_trip: number, };