// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Trip = { id: number, user_id: number, title: string, image: string | null, start_date: number, end_date: number, created_at: number, updated_at: number, };
